### ISSUE TITLE
nextpnr-gowin -> ERROR: Incorrect chipdb version 1 is used. Version 2 is required

### ISSUE THREAD

**Issue by federico-borello** [YosysHQ/nextpnr#1057]
I'm new to this, this is my first issue generated. 
hope it's somewhat relevant and helpful

#Error generated while 'making' apicula's blinky example. Yosys .json working well. nextpnr chipdb failure.
 
Version:
`nextpnr-gowin --version
nextpnr-gowin -- Next Generation Place and Route (Version nextpnr-0.4-47-gdb25c5c8)
`

Command:
`nextpnr-gowin --json blinky-tangnano9k-synth.json --write blinky-tangnano9k.json --device GW1NR-LV9QN88PC6/I5 --family GW1N-9C --cst tangnano9k.cst`

Command Output:
`ERROR: Incorrect chipdb version 1 is used. Version 2 is required
0 warnings, 1 error
make: *** [Makefile:17: blinky-tangnano9k.json] Error 255
`

Solved if version 0.3 of nextpnr is used

**Comment by gatecat** [comment]
Have you tried updating apycula and rebuilding?

**Comment by gatecat** [comment]
cc @pepijndevos @yrabbit

**Comment by pepijndevos** [comment]
For now install version 0.5.1a1

I've made a new release which will be on pypi in a few hours if all goes well.

**Comment by federico-borello** [comment]
Perfect, after installing latest apycula from pypi works with the latest nextpnr version.
thank you!

![image](https://user-images.githubusercontent.com/84739440/206301145-e262b228-4cb9-4345-88a0-e461341b865f.png)
