### ISSUE TITLE
Which pins work for SB_GB_IO with ice40up5k sg48?

### ISSUE THREAD

**Issue by osresearch** [YosysHQ/nextpnr#1093]
![image](https://user-images.githubusercontent.com/3068843/217075558-dbbfbf41-2026-43cf-8d7b-986c025e3352.png)

According to the data sheet, there are several pins that work with the global buffers in the ice40up5k, but when I try to create an `SB_GB_IO` structure with a simple test:
```
module top(
        output led_r,
        input `PIN
);
        wire clk;
        SB_GB_IO #(
                .PIN_TYPE(6'b000000),
                .IO_STANDARD("SB_LVDS_INPUT")
        ) differential_clock_input (
                .PACKAGE_PIN(`PIN),
                .GLOBAL_BUFFER_OUTPUT(clk)
        );

        reg led_r;
        
        always @(posedge clk)
                led_r <= !led_r;
endmodule
```

the only values for `PIN` that work are `gpio_23` and `gpio_37`, neither of which are listed in that table.  Am I missing something in the documentation that defines which pins are suitable?

For the rest of them either yosys or nextpnr reports an error:
```

gpio_2: ERROR: BEL 'X8/Y0/io0' has no global buffer connection available
gpio_3: ERROR: BEL 'X9/Y0/io1' has no global buffer connection available
gpio_4: ERROR: BEL 'X9/Y0/io0' has no global buffer connection available
gpio_6: ERROR: BEL 'X13/Y0/io1' has no global buffer connection available
gpio_9: ERROR: BEL 'X15/Y0/io0' has no global buffer connection available
gpio_11: ERROR: BEL 'X17/Y0/io0' has no global buffer connection available
gpio_12: ERROR: BEL 'X18/Y0/io0' has no global buffer connection available
gpio_13: ERROR: BEL 'X19/Y0/io0' has no global buffer connection available
gpio_18: ERROR: BEL 'X22/Y0/io1' has no global buffer connection available
gpio_19: ERROR: BEL 'X21/Y0/io1' has no global buffer connection available
gpio_21: ERROR: BEL 'X18/Y0/io1' has no global buffer connection available
gpio_25: ERROR: BEL 'X19/Y31/io1' has no global buffer connection available
gpio_26: ERROR: BEL 'X18/Y31/io0' has no global buffer connection available
gpio_27: ERROR: BEL 'X18/Y31/io1' has no global buffer connection available
gpio_28: ERROR: BEL 'X17/Y31/io0' has no global buffer connection available
gpio_31: ERROR: BEL 'X16/Y31/io1' has no global buffer connection available
gpio_32: ERROR: BEL 'X16/Y31/io0' has no global buffer connection available
gpio_34: ERROR: BEL 'X13/Y31/io1' has no global buffer connection available
gpio_35: ERROR: Bel 'X12/Y31/io1' can't be used for LVDS
gpio_35: ERROR: Bel 'X12/Y31/io1' of type 'SB_IO' is not valid for cell 'differential_clock_input' of type 'SB_IO'
gpio_36: ERROR: BEL 'X9/Y31/io1' has no global buffer connection available
gpio_38: ERROR: BEL 'X8/Y31/io1' has no global buffer connection available
gpio_42: ERROR: BEL 'X8/Y31/io0' has no global buffer connection available
gpio_43: ERROR: BEL 'X9/Y31/io0' has no global buffer connection available
gpio_44: ERROR: Bel 'X6/Y0/io1' can't be used for LVDS
gpio_44: ERROR: Bel 'X6/Y0/io1' of type 'SB_IO' is not valid for cell 'differential_clock_input' of type 'SB_IO'
gpio_45: ERROR: BEL 'X7/Y0/io1' has no global buffer connection available
gpio_46: ERROR: BEL 'X5/Y0/io0' has no global buffer connection available
gpio_47: ERROR: BEL 'X6/Y0/io0' has no global buffer connection available
gpio_48: ERROR: BEL 'X7/Y0/io0' has no global buffer connection available
```

**Comment by smunaut** [comment]
Are you sure the UP5k supports LVDS input for global buffers at all ?
Try in single ended mode.

The pins that should support it are : 

* G0/46B  pin 35
* G1/45A  pin 37 
* G3/25B  pin 20
* G6/3B   pin 44

**Comment by osresearch** [comment]
![35397d305d963377](https://user-images.githubusercontent.com/3068843/218249632-aa9dcc3f-90dd-4838-a82d-afcb8ab85a46.jpeg)

I can't find any details about the ice40up5k LVDS specifically, although experimentally it works with pin 37.  I'm able to drive the global buffer from the TMDS clock and route it into the PLL to reconstruct the bit-clock of the HDMI signal.

My confusion was based on the different naming conventions -- this spreadsheet from Lattice maps the `G1/45A` to pin 37/34 pair: https://www.latticesemi.com/-/media/LatticeSemi/Documents/PinPackage/iCE/iCE40UP-5k-Pinout.ashx?document_id=51971

(This doesn't explain why nextpnr let me use pin 23 to feed the global buffer; it looks like 20/13 are the right pair based on the spreadsheet, although for some reason the upduino doesn't route that pair to the outside?)

**Comment by smunaut** [comment]
Ok, just checked and actually pin 23 ( IO tile 19/31/0 ) and also pin 41 ( IO tile 19/31/0 ) should have connections to global buffers even though the lattice doc/pinout doesn't say.   Haven't actually tried them on HW though.

**Comment by osresearch** [comment]
And as another hard learned lesson: pin 35 is not available for input if the PLL is used. This is mentioned in [the sysCLOCK PLL appnote](https://www.latticesemi.com/-/media/LatticeSemi/Documents/ApplicationNotes/IK2/FPGA-TN-02052-1-4-iCE40-sysCLOCK-PLL-Design-User-Guide.ashx?document_id=47778) in the "Lattice Radiant Software" section in an offhand way:

> When PLL is instantiated, the GPLL pin cannot be used as other input connection - For example, setting "rstn" in the design to pin 35; it can only drive the PLL Reference clock. However, the GPLL pin can still be set as output

**Comment by smunaut** [comment]
Yes. Sams is true for the complement pin (  pin 37 ) which is also blocked for inputs if you use the second output of the PLL.

Pin 23/41 might also be blocked if you use global out on the HFOSC/LFOSC respectively too. I'm not 100% about that though.
