### ISSUE TITLE
Release 0.4 and 0.5 of nextpnr-ecp5 requires unreleased prjtrellis

### ISSUE THREAD

**Issue by zeldin** [YosysHQ/nextpnr#1104]
Since 0.4 nextpnr requires pytrellis to have the `split_slice_mode` kwarg to `make_dedup_chipdb`.  This argument was added to prjtrellis on March 31 last year, which is one month after the latest prjtrellis release (1.2.1).  This means that the current release of nextpnr-ecp5 can not be built unless you install an unreleased prjtrellis, which is a rather unfortunate state of affairs.  It's fine for nextpnr master to require prjtrellis master, but a release should really work with a release, IMHO.  :smile_cat:

**Comment by gatecat** [comment]
Thanks for pointing this out, I've created https://github.com/YosysHQ/prjtrellis/releases/tag/1.3.
