### ISSUE TITLE
Can't install, Could NOT find Boost (manjaro linux)

### ISSUE THREAD

**Issue by lukaspfitscher** [YosysHQ/nextpnr#1136]
cmake . -DARCH=gowin -DGOWIN_BBA_EXECUTABLE=/home/lukas/.local/bin/gowin_bba
-- Building with IPO
-- Found Python3: /usr/bin/python3.10 (found suitable version "3.10.10", minimum required is "3.5") found components: Interpreter 
-- Found Python3: /usr/include/python3.10 (found suitable version "3.10.10", minimum required is "3.5") found components: Development Development.Module Development.Embed 
CMake Error at /home/lukas/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR filesystem program_options
  iostreams system thread)
Call Stack (most recent call first):
  /home/lukas/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /home/lukas/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/FindBoost.cmake:2377 (find_package_handle_standard_args)
  CMakeLists.txt:190 (find_package)

**Comment by gatecat** [comment]
Hi, can you provide a bit more information about which boost packages you installed?
