### ISSUE TITLE
Nextpnr error, Internal Error: Assertion failure

### ISSUE THREAD

**Issue by yangrun369** [YosysHQ/nextpnr#1167]
When I import a JSON file from the GUI interface, an error is reported as follows：

![nextpnr_error](https://github.com/YosysHQ/nextpnr/assets/134853466/587b9c3d-e57e-4e8e-9487-47a2934ad423)

I installed msys2 on a Windows 10 x64 system and then installed  synthesize tools such as yosys and nextpnr；

**Comment by rowanG077** [comment]
Can you attach a reproducer?
