### ISSUE TITLE
ERROR: Assert `src_wire != WireId()' failed in nextpnr/common/router1.cc:869.

### ISSUE THREAD

**Issue by smunaut** [YosysHQ/nextpnr#117]
If you have an `inout` wire on the top level that's not connected to anythng in the design, this will trigger the assert in the title when checking the routing in next-pnr.

Minimal test case : 

```
module bug (
    inout wire gpio
);

endmodule
```

**Comment by whitequark** [comment]
Workaround (thanks @daveshah1):
```diff
diff --git a/common/router1.cc b/common/router1.cc
index 198461b..476b2ae 100644
--- a/common/router1.cc
+++ b/common/router1.cc
@@ -868,7 +868,8 @@ bool Context::checkRoutedDesign() const
         }
 
         auto src_wire = ctx->getNetinfoSourceWire(net_info);
-        log_assert(src_wire != WireId());
+        if (src_wire == WireId())
+            continue;
 
         if (net_info->wires.count(src_wire) == 0) {
             if (ctx->debug)
```

**Comment by smunaut** [comment]
Also related, if the `inout` port is used as output only you get a different assertion failure:

`nextpnr-ice40: nextpnr/json/jsonparse.cc:631: void nextpnr_ice40::JsonParser::insert_iobuf(nextpnr_ice40::Context*, nextpnr_ice40::NetInfo*, nextpnr_ice40::PortType, const string&): Assertion `net->driver.cell->type == ctx->id("$nextpnr_iobuf")' failed.`
