### ISSUE TITLE
Undefined refrence to lib_tty, openpty, forkpty, dlopen, dlsym and dlerror while running make command for nextpnr generic

### ISSUE THREAD

**Issue by Asma-Mohsin** [YosysHQ/nextpnr#1176]
Undefined refrence to lib_tty, openpty, forkpty, dlopen, dlsym and dlerror while running make command for nextpnr generic

![Screenshot from 2023-06-12 10-42-31](https://github.com/YosysHQ/nextpnr/assets/65780913/431530fe-a8d9-464a-a729-bee5557c1fa7)

**Comment by rowanG077** [comment]
@Asma-Mohsin Is this still and issue for you or is it resolved?

**Comment by Asma-Mohsin** [comment]
Its solved. Actually I was using Ubuntu 20.04 and I think it was dependencies issue. I upgraded my Ubuntu version to 22.04 and all such errors were solved.

**Comment by rowanG077** [comment]
@gatecat This can be closed.
