### ISSUE TITLE
No rule to make target 'path'

### ISSUE THREAD

**Issue by philiprbrenan** [YosysHQ/nextpnr#1188]
I am compiling **nextpnr** for **gowin** as a github action as shown in:

```https://github.com/philiprbrenan/nextPnr/actions/runs/5565129972/jobs/10165241477#step:3:148```

Processing terminates with the message:

```
 -- Build files have been written to: /home/runner/work/nextPnr/nextPnr/nextpnr-master
make[2]: *** No rule to make target 'path', needed by 'gowin/chipdb/chipdb-GW1N-1.bba'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:255: gowin/CMakeFiles/chipdb-gowin-bbas.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

Please tell me how I can proceed further with this compilation?

**Comment by yrabbit** [comment]
You took it too literally. path here is the full path to gowin_bba like /usr/local/bin/gowin_bba as I have it.

https://github.com/philiprbrenan/nextPnr/blob/651fb14da5ca60a94c62d84d1abd7e11136b58eb/.github/workflows/main.yml#L30
