### ISSUE TITLE
Assertion failure: init != "" (/path/to/nextpnr/ice40/bitstream.cc:778)

### ISSUE THREAD

**Issue by olofk** [YosysHQ/nextpnr#121]
I'm hitting an assertion failure with cfaa6c0e5de72e25da996f1fcda1d9caa58e4d1f (have not tried other versions). Don't have the time to create a minimal example now, but I can try to provide that later if required. In the meantime, I'm attaching the synthesized project in the hope that it's something easy to figure out. `make serv_0.bin` should do the trick. Shout if you need the source tree as well
[tinyfpga_bx-icestorm.tar.gz](https://github.com/YosysHQ/nextpnr/files/2589212/tinyfpga_bx-icestorm.tar.gz)

**Comment by daveshah1** [comment]
It seems that I mistakenly added that assertion for debugging, and it was only tested with Yosys inferred BRAM which always have INIT parameters on them. Can you check that it works with the assertion removed?

**Comment by olofk** [comment]
That seems to work just fine. Thanks!
