### ISSUE TITLE
ERROR: clearing already set config bit NegClk

### ISSUE THREAD

**Issue by donotnoot** [YosysHQ/nextpnr#1210]
I'm running into this error and I have no idea why. I've found the string in the codebase but I'm not good enough at C++ to figure out what exactly triggers it. I'm extremely new to FPGAs so there is a fair chance that I'm just doing something completely wrong :) but I tried searching online for this error and Google told me there are zero results for it so I'm very lost.

I've been struggling with this error for a few days, and it comes and goes. Sometimes if I comment out some section of the code it goes away but then if I write some more code it comes back, and again since I'm very new to FPGAs I have no idea why. The error does not provide much context so I don't even know what makes it come and go away. 

The error is coming from this, after running Yosys to generate the JSON file:

```
nextpnr-ice40 --Werror --lp1k --package qn84 --freq 50 --pcf pins.pcf --asc build/top.asc --json build/top.json
```

The JSON file is massive so I won't paste it here, I'm attaching it as top.txt. The top.asc is attached as asc.txt. Github wouldn't let me attach files with json and asc extensions for some reason, that's why they have the txt extension. I also pushed the whole thing [to this Git repo](https://git.sr.ht/~rf/nextpnr_error/tree), if anyone wants to look at the whole project.

I compiled the tools from the latest Git tags:
```
~ % yosys --version
Yosys 0.32 (git sha1 fbab08acf, clang 15.0.7 -fPIC -Os)
~ % nextpnr-ice40 --version
"nextpnr-ice40" -- Next Generation Place and Route (Version nextpnr-0.6)
```

Thanks in advance.

[asc.txt](https://github.com/YosysHQ/nextpnr/files/12517140/asc.txt)

[top.txt](https://github.com/YosysHQ/nextpnr/files/12517134/top.txt)

**Comment by gatecat** [comment]
Thanks for reporting! This should hopefully be reliably fixed by https://github.com/YosysHQ/nextpnr/pull/1212
