### ISSUE TITLE
Import Error ECP5, But ICE40 is ok.  Can you give me some advice?

### ISSUE THREAD

**Issue by ZhangPeterGree** [YosysHQ/nextpnr#1226]
sudo cmake -DARCH=ecp5 -DTRELLIS_INSTALL_PREFIX=/usr/local . -DCMAKE_INSTALL_PREFIX=/ -DCMAKE_POLICY_DEFAULT_CMP0094=NEW; sudo make -j 4; sudo make install

-- Building with IPO
-- Found Python3: /home/mt/miniconda3/envs/litexEnv/include/python3.8 (found suitable version "3.8.18", minimum required is "3.5") found components: Development Development.Module Development.Embed 
-- Found Boost: /usr/include (found version "1.83.0") found components: filesystem program_options iostreams system thread regex chrono atomic 
-- Found Boost: /usr/include (found version "1.83.0") found components: program_options filesystem system 
-- Configuring architecture: ecp5
-- Enabled ECP5 devices: 25k;45k;85k
-- Found Python3: /home/mt/miniconda3/envs/litexEnv/bin/python3.8 (found suitable version "3.8.18", minimum required is "3.5") found components: Interpreter 
-- Trellis install prefix: /usr/local
-- Trellis library directory: /usr/local/lib/trellis
-- Trellis data directory: /usr/local/share/trellis
-- Using ECP5 chipdb: /home/mt/litexEnv/nextpnr/ecp5/chipdb
-- Configuring done (1.5s)
-- Generating done (0.0s)
-- Build files have been written to: /home/mt/litexEnv/nextpnr
[  1%] Generating chipdb/chipdb-25k.bba
[  4%] Built target bbasm
Traceback (most recent call last):
  File "/home/mt/litexEnv/nextpnr/ecp5/trellis_import.py", line 21, in <module>
    import pytrellis
ImportError: /home/mt/miniconda3/envs/litexEnv/lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/mt/litexEnv/nextpnr/ecp5/pytrellis.so)
make[2]: *** [ecp5/CMakeFiles/chipdb-ecp5-bbas.dir/build.make:77: ecp5/chipdb/chipdb-25k.bba] Error 1
make[1]: *** [CMakeFiles/Makefile2:255: ecp5/CMakeFiles/chipdb-ecp5-bbas.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
[  1%] Generating chipdb/chipdb-25k.bba
Traceback (most recent call last):
  File "/home/mt/litexEnv/nextpnr/ecp5/trellis_import.py", line 21, in <module>
    import pytrellis
ImportError: /home/mt/miniconda3/envs/litexEnv/lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/mt/litexEnv/nextpnr/ecp5/pytrellis.so)
make[2]: *** [ecp5/CMakeFiles/chipdb-ecp5-bbas.dir/build.make:77: ecp5/chipdb/chipdb-25k.bba] Error 1
make[1]: *** [CMakeFiles/Makefile2:255: ecp5/CMakeFiles/chipdb-ecp5-bbas.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

ldd -v nextpnr-ice40                                                                                                                               
	linux-vdso.so.1 (0x00007ffd6ead0000)
	libtbb.so.12 => /usr/lib/libtbb.so.12 (0x00007fedd1c9e000)
	libboost_filesystem.so.1.83.0 => /usr/lib/libboost_filesystem.so.1.83.0 (0x00007fedd1c79000)
	libboost_program_options.so.1.83.0 => /usr/lib/libboost_program_options.so.1.83.0 (0x00007fedd1c34000)
	libboost_iostreams.so.1.83.0 => /usr/lib/libboost_iostreams.so.1.83.0 (0x00007fedd1c1d000)
	libboost_system.so.1.83.0 => /usr/lib/libboost_system.so.1.83.0 (0x00007fedd1c18000)
	libboost_thread.so.1.83.0 => /usr/lib/libboost_thread.so.1.83.0 (0x00007fedd1bf7000)
	libboost_regex.so.1.83.0 => /usr/lib/libboost_regex.so.1.83.0 (0x00007fedc3dad000)
	libboost_chrono.so.1.83.0 => /usr/lib/libboost_chrono.so.1.83.0 (0x00007fedd1bec000)
	libboost_atomic.so.1.83.0 => /usr/lib/libboost_atomic.so.1.83.0 (0x00007fedd1be2000)
	libpython3.11.so.1.0 => /usr/lib/libpython3.11.so.1.0 (0x00007fedc3600000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fedc3200000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fedc3cc0000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fedc3c9b000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fedc2e00000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fedd1d15000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007fedc3c81000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007fedc3c6e000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007fedc3c3b000)
	libzstd.so.1 => /usr/lib/libzstd.so.1 (0x00007fedc352d000)
	libicudata.so.73 => /usr/lib/libicudata.so.73 (0x00007fedc0e00000)
	libicui18n.so.73 => /usr/lib/libicui18n.so.73 (0x00007fedc0a00000)
	libicuuc.so.73 => /usr/lib/libicuuc.so.73 (0x00007fedc0600000)

	Version information:
	./nextpnr-ice40:
		libgcc_s.so.1 (GCC_3.3.1) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.0) => /usr/lib/libgcc_s.so.1
		libm.so.6 (GLIBC_2.2.5) => /usr/lib/libm.so.6
		libm.so.6 (GLIBC_2.27) => /usr/lib/libm.so.6
		libm.so.6 (GLIBC_2.29) => /usr/lib/libm.so.6
		libc.so.6 (GLIBC_2.38) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.32) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.34) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
		libstdc++.so.6 (GLIBCXX_3.4.14) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.32) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.8) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.19) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.5) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.29) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.22) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.26) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.11) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.3) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.15) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.13) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.18) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.9) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.9) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.20) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.2) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.21) => /usr/lib/libstdc++.so.6
	/usr/lib/libtbb.so.12:
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /usr/lib64/ld-linux-x86-64.so.2
		libgcc_s.so.1 (GCC_3.0) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.3.1) => /usr/lib/libgcc_s.so.1
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.32) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.34) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
		libstdc++.so.6 (CXXABI_1.3.8) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.3) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.11) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.30) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.21) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.13) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4) => /usr/lib/libstdc++.so.6
	/usr/lib/libboost_filesystem.so.1.83.0:
		libgcc_s.so.1 (GCC_3.0) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.3.1) => /usr/lib/libgcc_s.so.1
		libc.so.6 (GLIBC_2.7) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.28) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.6) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.38) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.25) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
		libstdc++.so.6 (GLIBCXX_3.4.20) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.8) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.9) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.11) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.21) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.30) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4) => /usr/lib/libstdc++.so.6
	/usr/lib/libboost_program_options.so.1.83.0:
		libgcc_s.so.1 (GCC_3.0) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.3.1) => /usr/lib/libgcc_s.so.1
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
		libstdc++.so.6 (GLIBCXX_3.4.32) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.20) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.11) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.9) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.9) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.29) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.26) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.30) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.21) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4) => /usr/lib/libstdc++.so.6
	/usr/lib/libboost_iostreams.so.1.83.0:
		libgcc_s.so.1 (GCC_3.0) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.3.1) => /usr/lib/libgcc_s.so.1
		liblzma.so.5 (XZ_5.2) => /usr/lib/liblzma.so.5
		liblzma.so.5 (XZ_5.0) => /usr/lib/liblzma.so.5
		libstdc++.so.6 (GLIBCXX_3.4.9) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.9) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.21) => /usr/lib/libstdc++.so.6
		libc.so.6 (GLIBC_2.33) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libboost_thread.so.1.83.0:
		libgcc_s.so.1 (GCC_3.0) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.3.1) => /usr/lib/libgcc_s.so.1
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.34) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
		libstdc++.so.6 (GLIBCXX_3.4.11) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.9) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.9) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.30) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.21) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4) => /usr/lib/libstdc++.so.6
	/usr/lib/libboost_regex.so.1.83.0:
		libgcc_s.so.1 (GCC_3.0) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.3.1) => /usr/lib/libgcc_s.so.1
		libstdc++.so.6 (GLIBCXX_3.4.20) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.21) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.9) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.29) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.15) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.30) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4) => /usr/lib/libstdc++.so.6
		libc.so.6 (GLIBC_2.32) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.38) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
	/usr/lib/libboost_chrono.so.1.83.0:
		libstdc++.so.6 (GLIBCXX_3.4.21) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.9) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3) => /usr/lib/libstdc++.so.6
		libgcc_s.so.1 (GCC_3.0) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.3.1) => /usr/lib/libgcc_s.so.1
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.17) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libboost_atomic.so.1.83.0:
		libstdc++.so.6 (CXXABI_1.3) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.8) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.9) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4) => /usr/lib/libstdc++.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libpython3.11.so.1.0:
		libm.so.6 (GLIBC_2.38) => /usr/lib/libm.so.6
		libm.so.6 (GLIBC_2.35) => /usr/lib/libm.so.6
		libm.so.6 (GLIBC_2.29) => /usr/lib/libm.so.6
		libm.so.6 (GLIBC_2.2.5) => /usr/lib/libm.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.6) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.28) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.25) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.15) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.38) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.26) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.27) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.7) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.33) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.5) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.17) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.32) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.16) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.34) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.9) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libstdc++.so.6:
		libm.so.6 (GLIBC_2.2.5) => /usr/lib/libm.so.6
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /usr/lib64/ld-linux-x86-64.so.2
		libgcc_s.so.1 (GCC_4.2.0) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.4) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.3) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_4.3.0) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.0) => /usr/lib/libgcc_s.so.1
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.38) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.6) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.26) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.33) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.25) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.18) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.16) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.32) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.7) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.17) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.36) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.34) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libm.so.6:
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /usr/lib64/ld-linux-x86-64.so.2
		libc.so.6 (GLIBC_ABI_DT_RELR) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.35) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.34) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_PRIVATE) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libgcc_s.so.1:
		libc.so.6 (GLIBC_2.35) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.34) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libc.so.6:
		ld-linux-x86-64.so.2 (GLIBC_2.2.5) => /usr/lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /usr/lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /usr/lib64/ld-linux-x86-64.so.2
	/usr/lib/libz.so.1:
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
	/usr/lib/libbz2.so.1.0:
		libc.so.6 (GLIBC_2.3) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/liblzma.so.5:
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.32) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.34) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.6) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.17) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libzstd.so.1:
		libc.so.6 (GLIBC_2.34) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libicui18n.so.73:
		libstdc++.so.6 (CXXABI_1.3.8) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3) => /usr/lib/libstdc++.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
		libgcc_s.so.1 (GCC_3.0) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.3.1) => /usr/lib/libgcc_s.so.1
		libm.so.6 (GLIBC_2.29) => /usr/lib/libm.so.6
		libm.so.6 (GLIBC_2.2.5) => /usr/lib/libm.so.6
	/usr/lib/libicuuc.so.73:
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /usr/lib64/ld-linux-x86-64.so.2
		libm.so.6 (GLIBC_2.27) => /usr/lib/libm.so.6
		libm.so.6 (GLIBC_2.2.5) => /usr/lib/libm.so.6
		libm.so.6 (GLIBC_2.29) => /usr/lib/libm.so.6
		libgcc_s.so.1 (GCC_3.0) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.3.1) => /usr/lib/libgcc_s.so.1
		libstdc++.so.6 (CXXABI_1.3.8) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.11) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.30) => /usr/lib/libstdc++.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.33) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.34) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6

**Comment by rowanG077** [comment]
For whatever reason your install is using miniconda python + libc which is clashing with the rest of your system. Try to remove those from your build environment so it uses system Python.
