### ISSUE TITLE
Building himbaechel requires python 3.9+ but readme says 3.5

### ISSUE THREAD

**Issue by jeremyherbert** [YosysHQ/nextpnr#1244]
Hi,

In the nextpnr readme it says python 3.5 or higher is needed to build. However, there are a number of usages of python 3.9+ features in himbaechel, namely:

- `list[]`and `dict[]` typehints instead of `List[]` and `Dict[]`
- `importlib.resources.files` was added in 3.9

The solution is probably to just require python 3.9, but this will cut out ubuntu 20.04 users that have 3.8.10.

**Comment by gatecat** [comment]
README has been updated in https://github.com/YosysHQ/nextpnr/commit/55635cf2cda7af3a301da33293cc0094e7d540a6

If someone still using Ubuntu 20.04 without later Python is interested in making himbaechel support Python 3.8 and willing to give it a quick test, I would happily accept that as a PR.
