### ISSUE TITLE
 infinite loop in random_bel_for_cell() while placing rare resources

### ISSUE THREAD

**Issue by swetland** [YosysHQ/nextpnr#127]
Attached json is a small design (VGA character display and SPI interface to VRAM) that causes nextpnr-ice40 to get stuck forever.

[stuck.tar.gz](https://github.com/YosysHQ/nextpnr/files/2592066/stuck.tar.gz)

`$ nextpnr-ice40 --package sg48 --up5k --pcf top.pcf --asc top.asc --json top.json`

Discovered after resolving https://github.com/YosysHQ/nextpnr/issues/126 

May need fixes from @smunaut to get far enough to get stuck.

**Comment by smunaut** [comment]
Here's a proposed fix, not sure if it's the right approach but it makes sense to me and it works:

https://github.com/smunaut/nextpnr/commit/19c8a1f1c7f6991dcf2995566f47dd4df0f221d5
