### ISSUE TITLE
Cut a release with Gowin Himbaechel uarch

### ISSUE THREAD

**Issue by pepijndevos** [YosysHQ/nextpnr#1276]
Can we please have a nextpnr release that supports the Gowin himbaechel backend? It's been half a year since the last release.

We keep getting issues from people asking for devices that are already supported but not in any release version of nextpnr. 
We also carry a huge amount of legacy code to support nextpnr-gowin which is increasingly lagging behind, with no support for BRAM and the entire GW2A family of devices.

Currently the process for building nxtpnr-himbaechel with the Gowin uarch is uncodumented in either Nextpnr (which only mentions nextpnr-gowin) or Apicula (which just points to Nextpnr)

**Comment by gatecat** [comment]
Sounds good, I have this roughly planned for tomorrow unless anyone objects...

**Comment by gatecat** [comment]
[Done!](https://github.com/YosysHQ/nextpnr/releases/tag/nextpnr-0.7)

**Comment by pepijndevos** [comment]
Thanks!
