### ISSUE TITLE
I can't find the arch file chipdb-5k.bin, where is it ?

### ISSUE THREAD

**Issue by lehaifeng000** [YosysHQ/nextpnr#1316]
When using ice40, I found that the file chipdb-5k.bin was not found, but the size of nextpnr-ice40 is more than 300M. Is the arch content compiled into nextpnr-ice40 during compilation?

**Comment by gatecat** [comment]
Yes, that's correct, by default chipdbs are included in the binary so we don't have to worry about loading data at runtime.

**Comment by lehaifeng000** [comment]
thank you, if I want the chipdbs to be an independent file, what should I do?
