### ISSUE TITLE
Does anyone know how to get this working in Void Linux?

### ISSUE THREAD

**Issue by Xeraster** [YosysHQ/nextpnr#1321]
I get this error when running make:

> CMake Error at /usr/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find Python3 (missing: Python3_INCLUDE_DIRS Development
>   Development.Module Development.Embed) (found suitable version "3.12",
>   minimum required is "3.5")
> Call Stack (most recent call first):
>   /usr/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
>   /usr/share/cmake-3.27/Modules/FindPython/Support.cmake:3824 (find_package_handle_standard_args)
>   /usr/share/cmake-3.27/Modules/FindPython3.cmake:545 (include)
>   CMakeLists.txt:199 (find_package)

I spent all afternoon trying to either compile nextpnr or compile python 3.5 from source but was ultimately unsuccessful. Maybe there's something else I should be doing.

**Comment by whitequark** [comment]
If you have working Python, you could try installing [the YoWASP distribution](https://yowasp.org):

```
pip install yowasp-nextpnr-ice40
yowasp-nextpnr-ice40 --help
```

**Comment by gatecat** [comment]
The failure here is that it can't find Python with a minimum version of 3.5 (actually, this is probably out of date and newer is required now) and the right development headers - 3.12, as it's finding,  is definitely fine too just the development parts are missing - probably the relevant development package from your distribution must be installed.
