### ISSUE TITLE
Not meeting timing should be at least a warning

### ISSUE THREAD

**Issue by whitequark** [YosysHQ/nextpnr#137]
Right now `--freq` seems to be essentially advisory, and nextpnr would gladly make a design that's half as slow as requested, and not even display a warning. This is particularly an issue with `--quiet`.

**Comment by mithro** [comment]
I would say this should be an error!?

**Comment by mithro** [comment]
A `--allow-timing-failure` could make this a warning.

**Comment by cliffordwolf** [comment]
It's not an error in any of the vendor tools I know so no, it should not be an error.

**Comment by daveshah1** [comment]
Following further discussion with @whitequark, it seems like the best approach is for failing timing to be a non-fatal error that will proceed to bitstream generation, so PnR time is not wasted; but produce a non-zero return code at the end.
