### ISSUE TITLE
Symbol not found issue (macOS, nextpnr-himbaechel)

### ISSUE THREAD

**Issue by matiasilva** [YosysHQ/nextpnr#1401]
Running `nextpnr-himbaechel` after sourcing the env in the latest OSS suite build (1st dec) returns:

`symbol not found in flat namespace '___isPlatformVersionAtLeast'`.

macOS 15.1.1
Xcode 16.1

Has anyone run into this or know what might be causing it? Thanks!

**Comment by mmicko** [comment]
Issue is on oss-cad-suite-build side and it is fixed there now
