### ISSUE TITLE
undefined reference to symbol '_ZN5boost6system15system_categoryEv

### ISSUE THREAD

**Issue by uXeBoy** [YosysHQ/nextpnr#175]
Receive the following error when attempting: `make -j$(nproc)`

```
/usr/bin/ld: CMakeFiles/nextpnr-ice40.dir/common/project.cc.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
/usr/local/lib/libboost_system.so.1.60.0: error adding symbols: DSO missing from command line
```

**Comment by uXeBoy** [comment]
OK, was able to progress past this error by adding '**system**' to line 69 of CMakeLists.txt:

`set(boost_libs system filesystem thread program_options)`

But now getting a different error:

```
CMakeFiles/nextpnr-ice40.dir/ice40/arch.cc.o: In function `nextpnr_ice40::RelPtr<nextpnr_ice40::ChipInfoPOD>::get() const':
/home/dan/Downloads/nextpnr/ice40/arch.h:37: undefined reference to `nextpnr_ice40::chipdb_blob_1k'
/home/dan/Downloads/nextpnr/ice40/arch.h:37: undefined reference to `nextpnr_ice40::chipdb_blob_8k'
/home/dan/Downloads/nextpnr/ice40/arch.h:37: undefined reference to `nextpnr_ice40::chipdb_blob_384'
/home/dan/Downloads/nextpnr/ice40/arch.h:37: undefined reference to `nextpnr_ice40::chipdb_blob_5k'
collect2: error: ld returned 1 exit status
make[2]: *** [nextpnr-ice40] Error 1
make[1]: *** [CMakeFiles/nextpnr-ice40.dir/all] Error 2
make: *** [all] Error 2
```

Which seems related to [this](https://github.com/YosysHQ/nextpnr/issues/173) issue?

**Comment by daveshah1** [comment]
Did updating CMake also fix the ice40 link issue? Currently we have only tested nextpnr on Ubuntu 16.04 and later.

**Comment by uXeBoy** [comment]
Yes, it seems like those two issues were connected. But my machine ground to a halt and froze up a lot compiling the chipdb files, so I am uncertain they are valid... it would be great to be able to just download a verified precompiled copy of the chipdb-*.bba and chipdb-*.cc files somewhere??

**Comment by daveshah1** [comment]
Try these: http://ds0.me/ice40_chipdb.tar.xz

**Comment by janrinze** [comment]
using only 'make' instead of 'make -j$(nproc)' will reduce the chances of memory exhaustion during build.
If that works, try' 'make -j2' or 'make -j3' to see where it runs out of memory. The 'freezing' usually means that your machine has resorted to swapping.
