### ISSUE TITLE
compilation error with nextpnr where arachne-pnr works well

### ISSUE THREAD

**Issue by phheim** [YosysHQ/nextpnr#183]
The attached blif and json files where generated by yosys from the same source code. With arachne-pnr the blif file was compiled well, but the compilation of the json file by nextpnr terminated with an error. The log file can also be found below.

[report.tar.gz](https://github.com/YosysHQ/nextpnr/files/2690994/report.tar.gz)

**Comment by daveshah1** [comment]
Thank you for the error report and for including your design fixes. Can you double check that #184 works on hardware (if possible?

**Comment by phheim** [comment]
Thanks, it works.
