### ISSUE TITLE
-pullup yes causes pin defined in pcf to be unconstrained and not connected

### ISSUE THREAD

**Issue by janrinze** [YosysHQ/nextpnr#188]
having a pin defined in a pcf file with the " -pullup yes " flag fails to allocate the pin with nextpnr.

see attached file,

untar attached file in an empty directory
 yosys -q -p 'synth_ice40 -top top -json test.json' test.v
nextpnr-ice40 --pcf hx8k.pcf --json test.json --asc test.asc --hx8k

output:
Info: Importing module top
Info: Rule checker, verifying imported design
Info: Checksum: 0xade084ac

Info: constrained 'led1' to bel 'X17/Y33/io0'
Info: constrained 'led2' to bel 'X16/Y33/io1'
Info: constrained 'led3' to bel 'X17/Y0/io0'
Info: constrained 'pclk' to bel 'X16/Y0/io1'
Warning: unmatched constraint 'yes' (on line 10)

Info: Packing constants..
Info: Packing IOs..
Warning: IO 'button' is not constrained to a pin and will be automatically placed
Info: Packing LUT-FFs..
.......

The warning clearly shows that button is not properly assigned to the pin.
[nextpnrtest.tar.gz](https://github.com/YosysHQ/nextpnr/files/2700230/nextpnrtest.tar.gz)

**Comment by daveshah1** [comment]
See #189
