### ISSUE TITLE
Trying to build in macOS 10.14.2

### ISSUE THREAD

**Issue by enKoding** [YosysHQ/nextpnr#190]
> cmake -DARCH=ice40 . -DICEBOX_ROOT=/usr/local/bin/icebox
> make -j$(nproc)
...
4 warnings generated.
[ 51%] Linking CXX static library libQtPropertyBrowser.a
[ 51%] Built target QtPropertyBrowser
[ 52%] Linking CXX executable bbasm
[ 52%] Built target bbasm
make[2]: *** No rule to make target `/usr/local/bin/icebox/chipdb-8k.txt', needed by `ice40/chipdbs/chipdb-8k.bba'.  Stop.
make[1]: *** [CMakeFiles/ice40_chipdb.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 54%] Linking CXX static library libgui_ice40.a
[ 54%] Built target gui_ice40
make: *** [all] Error 2

**Comment by daveshah1** [comment]
Set ICEBOX_ROOT to `/usr/local/share/icebox`

**Comment by mmicko** [comment]
You need to git clone and install  https://github.com/cliffordwolf/icestorm in order to have chip database files for ice40

**Comment by enKoding** [comment]
Worked like a charm... You rock man !

**Comment by daveshah1** [comment]
Clarification added in 8f5d500.
