### ISSUE TITLE
Missing libraries on Debian testing

### ISSUE THREAD

**Issue by daveshah1** [YosysHQ/nextpnr#198]
Found at WTFPGA

Needed to add pthread, dl and util libraries to cmake_link_libraries for it to link without python-related undefined symbols.

**Comment by fred260571** [comment]
Hello
Could you tell me how to add pthread, dl and util libraries to cmake_link_libraries ?
My very bad solution is to remove python
`cmake -DARCH=ice40 -DICEBOX_ROOT=/usr/local/share/icebox  -DCMAKE_INSTALL_PREFIX=/usr/local . -DBUILD_PYTHON=OFF -DBUILD_GUI=OFF`

**Comment by nalzok** [comment]
There is a similar issue on macOS, see #322
