### ISSUE TITLE
Ring oscillator fails with NextPNR

### ISSUE THREAD

**Issue by Mecrisp** [YosysHQ/nextpnr#203]
I wish to switch from Arachne-PNR to NextPNR, but my design contains a ring oscillator for random number generation.

Arachne-PNR is fine with it, but NextPNR fails with "ERROR: timing analysis failed due to presence of combinatorial loops, incomplete specification of timing ports, etc." even when launching with the --no-tmdriv option.

How can I place and route ring oscillators with NextPNR ? I include a minimal example.

[ringosc.v.txt](https://github.com/YosysHQ/nextpnr/files/2727389/ringosc.v.txt)
[ringosc.pcf.txt](https://github.com/YosysHQ/nextpnr/files/2727392/ringosc.pcf.txt)
[compile.txt](https://github.com/YosysHQ/nextpnr/files/2727393/compile.txt)

I would prefer if I could use timing driven routing for most of the design and just denote the ring oscillator as "do not care".

**Comment by daveshah1** [comment]
You can use `--force` to override this warning (

**Comment by Mecrisp** [comment]
Thank you, up and running now.
