### ISSUE TITLE
ERROR: Cell '$gbuf_SB_GB_IO_io' cannot be bound to bel 'X0/Y17/gb' since it is already bound to cell '$gbuf_SB_PLL40_CORE_pllout_b'

### ISSUE THREAD

**Issue by whitequark** [YosysHQ/nextpnr#229]
To reproduce, use this archive: [vga-output.zip](https://github.com/YosysHQ/nextpnr/files/2847603/vga-output.zip)

I don't entirely understand the nature of the bug. I think it's related to global promotion. The error message refers to (a) a bel that has never been mentioned in the log before, and (b) an internal name of a global buffer that has never been mentioned in the log before, so at least the error message is wrong. 

But, I also don't know how to make the design work; switching to PLLOUTGLOBAL instead of PLLOUTCORE has no effect.

**Comment by daveshah1** [comment]
Thanks for the report and testcase!

#230 fixes the problem, if possible it would be much appreciated if you could confirm this works on hardware.

BTW there is no `PLLOUTGB` port so the testcase as is doesn't synthesise, but changing it to either `PLLOUTCORE` or `PLLOUTGLOBAL` works now (and didn't before). cc @eddiehung if you are adding this to the regressions.

**Comment by whitequark** [comment]
> BTW there is no `PLLOUTGB` port so the testcase as is doesn't synthesise, but changing it to either `PLLOUTCORE` or `PLLOUTGLOBAL` works now (and didn't before).

I archived the wrong file, sorry. This was a typo.

**Comment by whitequark** [comment]
@daveshah1 BTW, can you confirm what happens with the SB_IO that is eaten by the PLL? Is it correctly placed into high-Z statea? Is the pullup enabled?

**Comment by daveshah1** [comment]
It will be high-Z (unless an output is used at that location), and the pullup enabled as is the default unused IO (placing an IO at this location with the input unused and the pullup disabled should override this if needed, but I haven't tested)

**Comment by eddiehung** [comment]
Testcase added to https://github.com/YosysHQ/nextpnr-tests/commit/d3d81370e33cab1e2a0c74f0a334d17c80a0ee18
