### ISSUE TITLE
Feature request: --quiet mode

### ISSUE THREAD

**Issue by whitequark** [YosysHQ/nextpnr#25]
Most of the time, Glasgow designs will place and route successfully and within reasonable time, so progress messages aren't very interesting. The only really interesting part is Fmax. It'd be nice if nextpnr had a mode like arachne-pnr -q which only kept errors on console (but still wrote them to a logfile).

**Comment by mmicko** [comment]
Implemented in 6b6a0c6d3c0d39afecd3c0c6bd0e0a4c006adc5f. It displays only errors in quiet mode right now.

**Comment by whitequark** [comment]
Thanks!

**Comment by whitequark** [comment]
@q3k What about still displaying Fmax?
