### ISSUE TITLE
Improve slack redistribution for timing improvement

### ISSUE THREAD

**Issue by eddiehung** [YosysHQ/nextpnr#27]
Currently, the `--slack_redist_iter #` option runs slack redistribution every # placement and routing iterations.

This operation walks all clock-to-clock paths in an attempt to:
1. (on its forward pass) compute the path slack, based on the current target Fmax
2. (on its backward pass) distribute this path slack evenly between all the net budgets on this path, where `budget = std::min(budget, net_delay + path_slack/path_length)`
3. (on its forward pass) record the minimum path slack across all paths, for possible use in computing next target Fmax (if `--freq 0` specified)

Currently, enabling slack redistribution does not appear to return a significant timing improvement.  Perhaps something more intelligent than evenly distributing any slack surplus may be beneficial...?

**Comment by gatecat** [comment]
Slack and budget based PnR has now been removed in favour of criticalities updated throughout placement/routing iterations, so this issue no longer applies.
