### ISSUE TITLE
Glasgow memory-onfi applet fails to route

### ISSUE THREAD

**Issue by emilazy** [YosysHQ/nextpnr#334]
@whitequark asked me to open this. Sorry, I don't have a good reduced example for this, but here's a tarball from Glasgow: [memory-onfi.tar.gz](https://github.com/YosysHQ/nextpnr/files/3642538/memory-onfi.tar.gz)

**Comment by whitequark** [comment]
The symptoms is that nextpnr dies with:
```
Warning: Failed to find a route for arc 0 of net $nextpnr_ICESTORM_LC_6$I3.
ERROR: Routing design failed.
```
and no further information.

**Comment by daveshah1** [comment]
I can reproduce, is a carry placement issue. Very impressed that this hasn't been hit before!

**Comment by daveshah1** [comment]
See  #335
