### ISSUE TITLE
Should setting CMAKE_INSTALL_PREFIX also affect chipdb location?

### ISSUE THREAD

**Issue by avahidi** [YosysHQ/nextpnr#351]
Installing icestorm & nextpnr to a non-standard location will cause nextpnr some confusion:

```
make -C icestorm install PREFIX=/opt/fpga
...
cmake -DARCH=ice40 -DCMAKE_INSTALL_PREFIX=/opt/fpga .
make
...
make[2]: *** No rule to make target '/usr/local/share/icebox/chipdb-u4k.txt', needed by 'ice40/chipdbs/chipdb-u4k.bba'.  Stop.
```
I can't get around this without manually modifying all build.make files.

`find -name build.make -exec sed -i s:/usr/local:/opt/fpga:g  {} \;`

Is this the expected behavior?

**Comment by smunaut** [comment]
You can manually define `ICEBOX_ROOT` to change that. But I agree that the default should probably ne` CMAKE_INSTALL_PREFIX` rather than the hardcoded `/usr/local`
