### ISSUE TITLE
Python binding for IdString

### ISSUE THREAD

**Issue by smunaut** [YosysHQ/nextpnr#430]
Trying to view an IdString in the python shell (like to see the 'Key' value in an IdMap) always results in :

TypeError: No to_python (by-value) converter found for C++ type: nextpnr_ice40::IdString

It would be nice if this was mapped to a python string.

**Comment by daveshah1** [comment]
This should happen for all IdStrings, looks like a wrapper is missing here.

**Comment by smunaut** [comment]
Just tried the fixes in that PR and although it fixes it for list(ctx.cells)[0][0]  it still happens for others :

>>> list(lc.ports)[0][0]

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: No to_python (by-value) converter found for C++ type: nextpnr_ice40::IdString

>>> list(lc.attrs)[0][0]

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: No to_python (by-value) converter found for C++ type: nextpnr_ice40::IdString

**Comment by daveshah1** [comment]
Thanks for spotting, should be fixed for all cases now.

**Comment by smunaut** [comment]
Yup, seems to all work now, tx !
