### ISSUE TITLE
Nextpnr generic no longer throws python exceptions on assertion errors

### ISSUE THREAD

**Issue by pepijndevos** [YosysHQ/nextpnr#484]
See https://github.com/YosysHQ/apicula/pull/13

Apicula used to rely on catching an assertion error when a duplicated wire was added. But recent versions of Nextpnr appear to just crash rather than throwing a Python exception. This has been worked around, but is rather unfortunate.

**Comment by daveshah1** [comment]
@mmicko can you look at this?

**Comment by daveshah1** [comment]
Closing since #485 has been merged.
