### ISSUE TITLE
Virtualbox Error in ubuntu 18.04

### ISSUE THREAD

**Issue by Dhyansaj** [YosysHQ/nextpnr#531]
Its great annoying to hear this. I have reinstalled ubuntu 18.04 and started installing apps that I need. Downloaded q4wine. But didnt open. When starting from terminel it says no file.......bla bla. Thought of installing virtualbox. The same error repeated.

![Screenshot 2020-12-04 08:47:18](https://user-images.githubusercontent.com/75462474/101117840-f05c7d00-360d-11eb-964e-4424ade9f05f.png)

**Comment by Dhyansaj** [comment]
Could you please solve this

**Comment by daveshah1** [comment]
I'm not sure I understand what the link with nextpnr is?

**Comment by Dhyansaj** [comment]
Can you try ?  Or will the issue be solved if i reinstalled ubuntu ?

**Comment by daveshah1** [comment]
I am trying to understand why you have filed this as an issue against nextpnr? Did the problem start when you installed nextpnr?  I don't use Ubuntu myself, and this isn't the right forum for general Ubuntu/Qt questions in any case.

**Comment by Xiretza** [comment]
https://github.com/YosysHQ/nextpnr/issues/375 is the second google result for `libQt5Core.so.5: cannot open shared object file: No such file or directory`, so they may have just blindly posted their problem into the first issue tracker they found.

**Comment by daveshah1** [comment]
@Xiretza I think you must be right. I guess it's free SEO though :D

![Screenshot from 2020-12-04 09-28-04](https://user-images.githubusercontent.com/5521177/101146580-13d5f680-3613-11eb-8ac4-b1f14ec56f0e.png)
