### ISSUE TITLE
Issue with NextPnr install

### ISSUE THREAD

**Issue by faarodriguezpi** [YosysHQ/nextpnr#533]
I have the following problem. On Ubuntu 20.04, I'm following the installing instructions for the Icestorm tools, specifically NextPnr place&route tool. The prerequsites were installed all correct, cloned the repository and ran `cmake -DARCH=ice40 -DCMAKE_INSTALL_PREFIX=/usr/local .` 

But when running the line:

`make -j$(nproc)`

It raises the errors:

```
/usr/bin/ld: /usr/local/lib/libpython3.5m.a(dynload_shlib.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: error al añadir símbolos: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/nextpnr-ice40.dir/build.make:577: nextpnr-ice40] Error 1
make[1]: *** [CMakeFiles/Makefile2:265: CMakeFiles/nextpnr-ice40.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

Thanks in advance.

**Comment by daveshah1** [comment]
I think the problem here is related to a local install of libpython3.5m.a; I'm not sure why this is being picked up on Ubuntu 20.04.
