### ISSUE TITLE
Assertion failure: pio == "PIOA" with nextpnr-ecp5 using LVCMOS33D

### ISSUE THREAD

**Issue by eduardosm** [YosysHQ/nextpnr#544]
nextpnr-ecp5 crashes with

```
terminate called after throwing an instance of 'nextpnr_ecp5::assertion_failure'
  what():  Assertion failure: pio == "PIOA" (nextpnr/ecp5/bitstream.cc:871)
```

Version:
```
nextpnr-ecp5 -- Next Generation Place and Route (Version c8cb9895)
```

Minimal example: 
[bug.zip](https://github.com/YosysHQ/nextpnr/files/5717621/bug.zip)

Changing `IO_TYPE=LVCMOS33D` to `LVCMOS33` in the LPF file prevents the failure.

**Comment by daveshah1** [comment]
I've added a better error message in 5e53a182

The solution here is only to drive gpdi_dp and to remove gpdi_dn; because LVCMOS33D implies a pseudo-differential driver that drives both sides of the pair (but must be placed on the 'A' side)
