### ISSUE TITLE
Instantiation of SB_GB_IO with `--pcf-allow-unconstrained` fails

### ISSUE THREAD

**Issue by bnossum** [YosysHQ/nextpnr#545]
### Description

Instantiating `SB_GB_IO` while unconstrained I/O is allowed leads to assertion failure. (There is an easy workaround, constrain the I/O. This is a good idea anyway).

### Version
`nextpnr-ice40 -- Next Generation Place and Route (Version 84c55f8)`

### Steps to reproduce the issue
Commands:

    yosys -p 'synth_ice40 -json top.json'  top.v > top_synth.log
    nextpnr-ice40 --hx4k --package tq144 --pcf-allow-unconstrained --pcf top.pcf -v --debug --json top.json --asc top.asc 

Source file: `top.v`

    module top ( input pad_clk, output fobar ); 
       SB_GB_IO pin_clk(.PACKAGE_PIN(pad_clk),.GLOBAL_BUFFER_OUTPUT(fobar));
    endmodule

Preference file: `top.pcf`

    # set_io pad_clk 20

### Expected behavior
Compilation success.

### Actual behavior
Assertion failure.

**Comment by daveshah1** [comment]
The various complexities around SB_GB placement mean dealing with this correctly in all cases is more effort than it's worth (in general, if you are using SB_GB_IO it's because you have a specific pinout in mind); but I've added a nicer error message in 74c4fa67
