### ISSUE TITLE
enhancement request: Add git tags

### ISSUE THREAD

**Issue by GNUtoo** [YosysHQ/nextpnr#611]
Hi,

Would it be possible to add git tags to enable GNU/Linux distributions to package icestorm more easily?

Denis.

**Comment by gatecat** [comment]
I plan to do a nextpnr release as soon as the next Yosys release (0.10) is out. As it stands nextpnr relies on newer Yosys than the last release, so a tag now is of limited value for packaging purposes.

**Comment by olofk** [comment]
Guess we can close this one now?
