### ISSUE TITLE
Dependency on Abseil making WASM/YoWASP builds impossible

### ISSUE THREAD

**Issue by whitequark** [YosysHQ/nextpnr#616]
Abseil (with CMake, at least) has a [hard dependency](https://github.com/abseil/abseil-cpp/blob/master/CMakeLists.txt#L98) on threading, which breaks builds on platforms without threads. The upstream [worked around this](https://github.com/abseil/abseil-cpp/issues/693) for Bazel builds but not CMake. Unfortunately, the workaround (or its CMake equivalent) fixes the immediate issue (no `-pthread`) but it doesn't actually let the build complete on platforms without atomics, at least not for the library that nextpnr wants to use.

**Comment by litghost** [comment]
@whitequark What's the CMake invocation to build for WASM?  Given the Bazel changes, it looks the right answer too change the `find_package(Threads REQUIRED)` to:

```
if(NOT ${CMAKE_SYSTEM_NAME} STREQUAL Emscripten)
  find_package(Threads REQUIRED)
endif()
```
etc.  But I cannot test this.

**Comment by whitequark** [comment]
> Given the Bazel changes, it looks the right answer is to change the `find_package(Threads REQUIRED)` to:

That doesn't help; there's a ton of references to atomics, which are not currently a part of WASI.

**Comment by litghost** [comment]
> > Given the Bazel changes, it looks the right answer is to change the `find_package(Threads REQUIRED)` to:
> 
> That doesn't help; there's a ton of references to atomics, which are not currently a part of WASI.
> 
> That said, the WASI build is done by [this script](https://github.com/YoWASP/nextpnr/blob/develop/build.sh).

Not only that, but in the entropy store is a mutex lock here: https://github.com/abseil/abseil-cpp/blob/master/absl/container/internal/hashtablez_sampler.h#L87

So I don't think the bazel rules will help here, as fundamentally the Swiss table just assumes a multi-core system.  Unfortunate :(
