### ISSUE TITLE
Cannot find `-lrt` when compiling with GCC on Windows.

### ISSUE THREAD

**Issue by cr1901** [YosysHQ/nextpnr#666]
Example output:

```
[1/1] Linking CXX executable nextpnr-ice40.exe
FAILED: nextpnr-ice40.exe
cmd.exe /C "cd . && C:\msys64\mingw64\bin\g++.exe -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-array-bounds -fPIC -O3 -g -pipe  @CMakeFiles\nextpnr-ice40.rsp -o nextpnr-ice40.exe -Wl,--major-image-version,0,--min
or-image-version                                                            ,0  && cd ."
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lrt
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

`librt` shouldn't be used at all on Windows. By running `cmake --debug-find`, I figured out that the build system was picking up a copy of `librt` meant for Cygwin/MSYS2 layer, and not for native Windows, at `C:/msys64/usr/lib`. Adding `-DCMAKE_IGNORE_PATH=C:/msys64/usr/lib` or equivalent path to the `cmake` command line is a workaround for now that has been working for me.

The bug isn't in nextpnr, but rather an [unconditional](https://github.com/abseil/abseil-cpp/blob/master/absl/base/CMakeLists.txt#L17) `find_library` within abseil-cpp. I'll fix this at some point if no one else does, but since the bug is in a submodule that is not frequently updated, I figured it's worth opening an issue for others.

**Comment by gatecat** [comment]
The abseil dependency was removed altogether in #718
