### ISSUE TITLE
nextpnr GUI resets device selection on json load

### ISSUE THREAD

**Issue by lethalbit** [YosysHQ/nextpnr#722]
I noticed while using the nextprn GUI, at least for ice40, there is a bug where if you don't select the device and package via the command line, and use the `New` menu option, that it will reset the device selection when it loads the design json file.

However setting the device, package, and specifying the pcf and json file via the command line work fine when using the gui.

The following is a video example: [https://youtu.be/lR2g4mB8I_4](https://youtu.be/lR2g4mB8I_4)

I've not been able to confirm this happens on other architectures other than what's being used for this project currently. Also nextpnr doesn't log anything to stdout/stderr when this happens.

**Comment by gatecat** [comment]
See  #723 for a hopeful fix
