### ISSUE TITLE
Output placer and router details files

### ISSUE THREAD

**Issue by y8j31** [YosysHQ/nextpnr#732]
Hi,
I am using the branch 'xc7' to place and route on my own FPGA fabric, I know this version is out of date. But is there any luck this version of nextpnr can output the placer and router details for debug purpose? For example, a file inlucdes the locations description after placing, and a file includes which net is left to be routed in the router.

Kind regards

**Comment by gatecat** [comment]
Hi!

This is an example Python script that dumps placement information that should be usable on that branch: https://github.com/YosysHQ/nextpnr/blob/xc7/python/dump_design.py

However, I'd definitely recommend you think about updating at some point - that branch is about 2.5 years old in a codebase that's 3 years old so there have been many improvements since then - a much faster analytical placer, countless bug fixes, a new router, more deterministic behaviour, a JSON backend that includes place and route information, etc.

**Comment by y8j31** [comment]
> Hi!
> 
> This is an example Python script that dumps placement information that should be usable on that branch: https://github.com/YosysHQ/nextpnr/blob/xc7/python/dump_design.py
> 
> However, I'd definitely recommend you think about updating at some point - that branch is about 2.5 years old in a codebase that's 3 years old so there have been many improvements since then - a much faster analytical placer, countless bug fixes, a new router, more deterministic behaviour, a JSON backend that includes place and route information, etc.

Hi gatecat,
Thanks a lot for your reply. Yes, I am thinking about the update once I have the time. Do you have any clues which branch I can start with to update and apply on my own fabric?
Cheers

**Comment by gatecat** [comment]
I would strongly recommend starting from the `master` branch. Although they are both somewhat more complicated than you are likely to need, both `nexus` and `mistral` are good examples of new arches demonstrating recent design patterns (like not packing LUTs and FFs together but having validity checks during placement for this). `generic` is a simpler base that might be more relevant from a database point of view.

**Comment by y8j31** [comment]
> I would strongly recommend starting from the `master` branch. Although they are both somewhat more complicated than you are likely to need, both `nexus` and `mistral` are good examples of new arches demonstrating recent design patterns (like not packing LUTs and FFs together but having validity checks during placement for this). `generic` is a simpler base that might be more relevant from a database point of view.

Can the GENERIC_SLICE in ```generic``` be modified into a single output F which is similar to what ice40 do? I am looking for a way to combine F LUT output and Q FF output.

**Comment by gatecat** [comment]
> Can the GENERIC_SLICE in generic be modified into a single output F which is similar to what ice40 do? I am looking for a way to combine F LUT output and Q FF output.

You can have both as the same wire, the default packer will never use both at once. They were separate only to support arches where they are physically different wires.

**Comment by Ravenslofty** [comment]
I suppose nowadays this could be achieved with the Viaduct framework.

**Comment by gatecat** [comment]
> I suppose nowadays this could be achieved with the Viaduct framework.

Indeed, this is going to land as #1015
