### ISSUE TITLE
GUI crash when reloading the same JSON file after routing in `nextpnr-ice40`

### ISSUE THREAD

**Issue by cr1901** [YosysHQ/nextpnr#737]
## How To Duplicate

1. Open `nextpnr-ice40 --gui` from the command line.
2. File > Open JSON > `nextpnr\ice40\examples\blinky\blinky.json`
3. _Without loading a PCF_, click the Pack, Assign (accept default 50.00 MHz), Place, and Route buttons in order. The design will route just fine.
4. File > Open JSON > `nextpnr\ice40\examples\blinky\blinky.json`
5. _Without loading a PCF_, click the Pack, Assign (accept default 50.00 MHz), and Place buttons in order. `nextpnr-ice40` will hang similarly to this image, and requires Task Manager or CTRL+C from the command line to exit:
   ![image](https://user-images.githubusercontent.com/6418027/123781911-c36e0100-d8a2-11eb-86f3-1c900c71e7d8.png)

## System Information

```sh
$ uname -a
MINGW64_NT-10.0-19042 DESKTOP-H0PMN4M 3.1.7-340.x86_64 2020-11-08 12:32 UTC x86_64 Msys
```

```sh
William@DESKTOP-H0PMN4M MINGW64 ~/Projects/FPGA
$ nextpnr-ice40 -V
nextpnr-ice40 -- Next Generation Place and Route (Version 78c96514)
```

## Extra Context

By loading a PCF in steps 1 and 5, I can duplicate the problem as described above. However, by loading a PCF in _step 5 only, but not step 1_, `nextpnr-ice40` will hang and eventually segfault (according to command line) without an empty error box.

**Comment by mmicko** [comment]
Thanks for reporting this. Thing is that loading JSON should in that case should clear all internal structures (which is not the case, and now it is also quite more complicated) and that would require large changes in code. For now I am disabling button for JSON loading (as it was initially made) so user is forced to run New project before loading json again. 
Will see if I can make it do that automatically.
