### ISSUE TITLE
Build error not caused by pthreads but rather the old cmake in my dists

### ISSUE THREAD

**Issue by mengstr** [YosysHQ/nextpnr#778]
On Ubuntu 18.04 and the latest "elementary OS" I couldn't build nexpnr even if I had installed all the prerequisites. (On a newer Ubuntu release I could build it without any problems.) The error logs pointed towards pthreads and some googling revealed that it might be caused by it apparently should be used with a compilation flag rather than a linker option nowadays. But that was just a red herring.

```
matseng@T420:~/Documents/nextpnr$ cmake . -DARCH=ice40
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
<snip>
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:5 (cmake_policy):
  Policy "CMP0079" is not known to this version of CMake.

-- Building with IPO
<snip>
-- Using iCE40 chipdb: /home/matseng/Documents/nextpnr/ice40/chipdb
-- Configuring incomplete, errors occurred!
See also "/home/matseng/Documents/nextpnr/CMakeFiles/CMakeOutput.log".
See also "/home/matseng/Documents/nextpnr/CMakeFiles/CMakeError.log".
```

The real culprit turned out to be the policy CMP0079 that was added to the cmake script `CMakeLists.txt` four months ago. That policy requires a cmake newer than the versions in the failing dists.

```
matseng@T420:~/Documents/nextpnr$ cmake --version
cmake version 3.10.2
```

The fix for the time being is to simply comment out the offending line in the beginning of the `CMakeLists.txt` like this:

```
cmake_minimum_required(VERSION 3.5)
project(nextpnr CXX C)

# Allow family.cmake add additional dependencies to gui_${family}.
#cmake_policy(SET CMP0079 NEW)    <--- HERE

# Enable IPO support.
cmake_policy(SET CMP0069 NEW)
```

At least it seems to work for me, but since I'm a total noob when it comes to cmake and what that particular policy does some unintended side effects might rear its ugly head some day. I guess @litghost that `git blame` points to as the author of the addition could tell.

**Comment by gatecat** [comment]
This should fail more meaningfully after #989
