### ISSUE TITLE
DCSC doesn't propagate clock constraints

### ISSUE THREAD

**Issue by thirtythreeforty** [YosysHQ/nextpnr#804]
#754 added support for ECP5's DCSC primitive, but clock constraints are not propagated through it. I have an input clock running at 350MHz, however the output clock is assigned a default:

```
Info: Annotating ports with timing budgets for target frequency 12.00 MHz
```

the clock net (`cap2`) erroneously passes timing:
```
Info: Max frequency for clock          'cap2_clk': 348.80 MHz (PASS at 12.00 MHz)
Info: Max frequency for clock '$glbnet$sdrio_clk': 75.08 MHz (PASS at 60.00 MHz)
Warning: Max frequency for clock  '$glbnet$cap1_clk': 346.38 MHz (FAIL at 350.02 MHz)
Info: Max frequency for clock  '$glbnet$init_clk': 333.11 MHz (PASS at 96.01 MHz)
```

**Comment by rowanG077** [comment]
@thirtythreeforty I know it's a while back. If you are still waiting for this please check if https://github.com/YosysHQ/nextpnr/pull/1090 works for you!
