### ISSUE TITLE
Lattice ECP5: ERROR: cell type 'mux21' is unsupported 

### ISSUE THREAD

**Issue by SiliconWizard** [YosysHQ/nextpnr#811]
Trying to use the MUX21 primitive.

Is this unsupported on purpose?
Is there a workaround?

**Comment by gatecat** [comment]
There isn't really a generic useful MUX2 in hardware. I expect in almost all cases the Lattice tools just turn it into a LUT implementing MUX functions.

The hardware mux primitives are PFUMX and L6MUX21 but these are only intended for use in LUT-MUX structures and not on their own.

**Comment by SiliconWizard** [comment]
OK thanks. I suppose that implementing 'MUX2' in pure HDL should yield the same hardware?

Lattice IPs use the MUX2 primitive a lot, and I'm actually trying to port one for use with Yosys/nextpnr-ecp5.

**Comment by gatecat** [comment]
Yeah, it should

**Comment by SiliconWizard** [comment]
Thanks - I found this page that lists all supported primitives, hoping it's up to date:
https://github.com/YosysHQ/nextpnr/blob/master/ecp5/docs/primitives.md
