### ISSUE TITLE
Yet another Linux Python Boost related build failure: PopOS edition

### ISSUE THREAD

**Issue by sedurCode** [YosysHQ/nextpnr#819]
I had this doozy yesterday when building nextpnr as part of the '[summon_fpga_tools](https://github.com/open-tool-forge/summon-fpga-tools)' script put together for the icebreaker fpga board. I was building on a fresh (and updated) install of PoPOS with functioning python3.9 and dependencies installed.

`Traceback (most recent call last):
  File "/home/<my_path_to_build_script>/summon-fpga-tools/nextpnr-e926cddca274423ea414e61a07deb785ee63c92d/ecp5/trellis_import.py", line 21, in <module>
    import pytrellis
ImportError: /lib/x86_64-linux-gnu/libboost_python39.so.1.74.0: undefined symbol: _Py_NewReference
make[2]: *** [ecp5/CMakeFiles/chipdb-ecp5-bbas.dir/build.make:84: ecp5/chipdb/chipdb-25k.bba] Error 1
make[1]: *** [CMakeFiles/Makefile2:659: ecp5/CMakeFiles/chipdb-ecp5-bbas.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....`

The error isn't in a fail to find libboost, like other have had, but a missing symbol t[hat I found one thread discussing](https://bugs.python.org/issue40989).
A switft google didn't yield a simple response / fix for this issue. 
Any suggestions on how to continue?

**Comment by gatecat** [comment]
Can you try pointing this to `YosysHQ/prjtrellis` instead https://github.com/open-tool-forge/summon-fpga-tools/blob/master/summon-fpga-tools.sh#L349 ? prjtrellis moved a while ago and it looks like sft hasn't been updated.

**Comment by sedurCode** [comment]
Yep, that worked a treat! 
Thanks @gatecat
