### ISSUE TITLE
Could not initialize GLX

### ISSUE THREAD

**Issue by ChSotiriou** [YosysHQ/nextpnr#896]
Just installed the OSS CAD Suite and nextpnr can't open the GUI. It exits with the following error.

![image](https://user-images.githubusercontent.com/14891082/150201855-4964b8a2-51ab-4452-9df8-4912c95eae2b.png)

Please let me know if further information is needed.

Edit:

After exporting `export QT_XCB_GL_INTEGRATION=none` a window does open up for a few seconds but then closes with the following error.

```
(OSS CAD Suite) ➜  ~ nextpnr-ice40 --gui
Warning: Use of default value for --package is deprecated. Please add '--package ' to arguments.
nextpnr-ice40: /work/_builds/linux-x64/nextpnr-ice40/nextpnr/3rdparty/imgui/imgui.cpp:2861: ImGuiIO& ImGui::GetIO(): Assertion `GImGui != __null && "No current context. Did you call ImGui::CreateContext() or ImGui::SetCurrentContext()?"' failed.
zsh: abort (core dumped)  nextpnr-ice40 --gui
```

**Comment by ChSotiriou** [comment]
Issue resolved by removing the OSS CAD Suite and compiling from source.

**Comment by mmicko** [comment]
Sorry for late reaction. If you could please provide which distribution are you using, in order to  try to replicate this and solve this for future. Thanks.

**Comment by ChSotiriou** [comment]
I'm using Arco Linux. The version of nextpnr that came with oss-cad-suite (installed from the AUR) is:

```
➜  /opt/oss-cad-suite/bin🔒 ./nextpnr-ice40 --version
nextpnr-ice40 -- Next Generation Place and Route (Version fd2d4a8f)
```
