### ISSUE TITLE
make -j$(nproc) error

### ISSUE THREAD

**Issue by gromas** [YosysHQ/nextpnr#920]
Hi.
I try setup enveronments with windows 10 wsl and get error while execute make command.

[100%] Linking CXX executable nextpnr-ecp5
/usr/src/nextpnr/ecp5/bitstream.cc: In function ‘write_bitstream’:
/usr/src/nextpnr/ecp5/bitstream.cc:634:6: note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
  634 | void write_bitstream(Context *ctx, std::string base_config_file, std::string text_config_file)
      |      ^
/usr/src/nextpnr/ecp5/baseconfigs.cc: In function ‘config_empty_lfe5u_85f’:
/usr/src/nextpnr/ecp5/baseconfigs.cc:523:6: note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
  523 | void config_empty_lfe5u_85f(ChipConfig &cc)
      |      ^
/usr/src/nextpnr/ecp5/baseconfigs.cc: In function ‘config_empty_lfe5u_45f’:
/usr/src/nextpnr/ecp5/baseconfigs.cc:190:6: note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
  190 | void config_empty_lfe5u_45f(ChipConfig &cc)
      |      ^
[100%] Built target nextpnr-ecp5

**Comment by gatecat** [comment]
Those are notes not errors, while ideally those functions should be replaced with data or something it's nothing to worry about.
