### ISSUE TITLE
CMake Error: cmake version 3.5.1

### ISSUE THREAD

**Issue by vijaypanchal** [YosysHQ/nextpnr#930]
cmake -DARCH=ice40 -DCMAKE_INSTALL_PREFIX=/usr/local .
-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:5 (cmake_policy):
  Policy "CMP0079" is not known to this version of CMake.

CMake Error at CMakeLists.txt:8 (cmake_policy):
  Policy "CMP0069" is not known to this version of CMake.

CMake Error at CMakeLists.txt:9 (include):
  include could not find load file:

    CheckIPOSupported

CMake Error at CMakeLists.txt:10 (check_ipo_supported):
  Unknown CMake command "check_ipo_supported".

-- Configuring incomplete, errors occurred!

**Comment by Ravenslofty** [comment]
Your CMake is very out of date; 3.5.1 is 6 years old.
