### ISSUE TITLE
nextpnr generic architecture seg faults when unbinding a wire

### ISSUE THREAD

**Issue by AbedFares** [YosysHQ/nextpnr#979]
I've just run simple.sh located under generic/examples. it works fine! Then I tried to unbind a wire in the postRoute script but it seg faults in line 390 in generic/arch.cc
I suspect that there is a missing condition on whether or not the "uarch" variable is nullptr or not. I tried adding this condition and it passed.
Attached is where exactly the condition should be and the seg fault that I've received.
![ReportIssue](https://user-images.githubusercontent.com/60389055/165304926-936e39b3-0ff2-4935-8515-2e4eb83870c1.PNG)

**Comment by gatecat** [comment]
Thanks for reporting, can you confirm that 20cfafa1 solves this?

**Comment by AbedFares** [comment]
Thanks for the reply. Yes, I confirm that it was solved!
